# Generated by Django 4.0.5 on 2023-03-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_task_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='year',
            field=models.IntegerField(default=2023, verbose_name='Year expected to be completed:'),
        ),
    ]
