# Generated by Django 4.0.5 on 2023-01-27 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_number', models.IntegerField(unique=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.course')),
            ],
        ),
    ]
