# Generated by Django 4.0.5 on 2023-01-27 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_commission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'verbose_name': 'Commission', 'verbose_name_plural': 'Commissions'},
        ),
    ]
