# Generated by Django 4.0.5 on 2023-01-27 07:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0005_tasks_to_evaluate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks_to_evaluate',
            options={'verbose_name': 'Task to Evaluate', 'verbose_name_plural': 'Tasks to Evaluate'},
        ),
        migrations.CreateModel(
            name='Terms_of_Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_delivery', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Max_points_Criteria_01', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Max_points_Criteria_02', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Max_points_Criteria_03', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Max_points_Criteria_04', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Max_points_Criteria_05', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Max_points_Criteria_06', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Max_points_Criteria_07', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Max_points_Criteria_08', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Max_points_Criteria_09', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Max_points_Criteria_10', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Criteria_01', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade.Terms_of_Delivery.Criteria_01+', to='grade.tasks_to_evaluate')),
                ('Criteria_02', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade.Terms_of_Delivery.Criteria_02+', to='grade.tasks_to_evaluate')),
                ('Criteria_03', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade.Terms_of_Delivery.Criteria_03+', to='grade.tasks_to_evaluate')),
                ('Criteria_04', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade.Terms_of_Delivery.Criteria_04+', to='grade.tasks_to_evaluate')),
                ('Criteria_05', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade.Terms_of_Delivery.Criteria_05+', to='grade.tasks_to_evaluate')),
                ('Criteria_06', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade.Terms_of_Delivery.Criteria_06+', to='grade.tasks_to_evaluate')),
                ('Criteria_07', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade.Terms_of_Delivery.Criteria_07+', to='grade.tasks_to_evaluate')),
                ('Criteria_08', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade.Terms_of_Delivery.Criteria_08+', to='grade.tasks_to_evaluate')),
                ('Criteria_09', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade.Terms_of_Delivery.Criteria_09+', to='grade.tasks_to_evaluate')),
                ('Criteria_10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade.Terms_of_Delivery.Criteria_10+', to='grade.tasks_to_evaluate')),
                ('comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.commission')),
            ],
            options={
                'verbose_name': 'Terms of Delivery',
                'verbose_name_plural': 'Terms of Delivery',
            },
        ),
    ]
