# Generated by Django 4.0.5 on 2023-01-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0007_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='url_delivery',
            new_name='URL_delivery',
        ),
    ]
