# Generated by Django 4.0.5 on 2023-02-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0010_alter_rating_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-id'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='terms_of_delivery',
            options={'ordering': ['-id'], 'verbose_name': 'Terms of Delivery', 'verbose_name_plural': 'Terms of Delivery'},
        ),
        migrations.AddField(
            model_name='terms_of_delivery',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terms_of_delivery',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
    ]
