# Generated by Django 4.0.5 on 2023-05-19 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apidecc', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='HiredEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apidecc.department')),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apidecc.job')),
            ],
        ),
    ]
