# Generated by Django 4.0.5 on 2022-10-30 19:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='story',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
