# Generated by Django 4.0.5 on 2023-01-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplan', '0003_alter_alimentos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentos',
            name='comida',
            field=models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Merienda', 'Merienda'), ('Cena', 'Cena')], default='Almuerzo', max_length=150),
        ),
    ]
