# Generated by Django 4.0.5 on 2023-01-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplan', '0004_alimentos_comida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='categoria',
            field=models.CharField(choices=[('Grasas', 'Grasas'), ('Frutas', 'Frutas'), ('Verduras', 'Verduras'), ('Cereales_Legumbres', 'Cereales y Legumbres'), ('Proteínas', 'Proteínas'), ('Lacteos', 'Lacteos'), ('Otros', 'Otros')], default='Otros', max_length=50, verbose_name='Tipo de alimento'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='comida',
            field=models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Merienda', 'Merienda'), ('Cena', 'Cena')], default='Almuerzo', max_length=150, verbose_name='Comida en la que se suele consumir'),
        ),
    ]
